channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.1.2
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.2.0
  - defusedxml==0.7.1
  - lightgbm==3.2.1
  - matplotlib==3.5.2
  - pandas==1.4.4
  - psutil==5.9.0
  - typing-extensions==4.3.0
name: mlflow-env
